#!/bin/ksh
#
# The %NAME%_$1_$2 Job
#
rm -f %NAME%_$1_$2_job
#
#################################################
# number of processors
#################################################

DET=$1
START_ENS=$2
END_ENS=$3

ini_date=%DATE_INI%
bd_date=%DATE_BD% 
h_int=%H_INT%

COSMO_DIR=%PROGRAM_DIR%
INPUT_DIR=%INPUT_DIR%
OUTPUT_DIR=%OUTPUT_DIR%
ANALYSIS_DIR=%ANALYSIS_DIR%
LOG_DIR=%LOG_DIR%

NPX=20
NPY=12
NPIO=0
CPN=24              # cores per node
NP1=`expr $NPX \* $NPY`
NP=`expr $NP1 + $NPIO`
N1=`expr $NP + $CPN - 1`
NODES=`expr $N1 \/ $CPN` # number of physical nodes

TIMESTEPS=`echo |awk '{print a * 3600 / 2}' a=${h_int}`


## begin of LOOP
## also account for det run
I=$START_ENS
N_LOOP=$END_ENS
if [ $DET == true ]; then
  ((N_LOOP=N_LOOP+1))
fi
until [[ $I -gt $N_LOOP ]]; do
  if [ $I -ge 10 ]; then
    Iens=0${I}
  else
    Iens=00${I}
  fi
  
  if [ $DET == true -a $I -eq $N_LOOP ]; then
    edir=det
    EPS=.FALSE.
  else
    edir=ens${Iens}
    EPS=.TRUE.
  fi
  work_dir=$INPUT_DIR/${edir}
  INI_DIR=$INPUT_DIR/${edir}
  BD_DIR=$INPUT_DIR/${edir}
  OBS_DIR=$INPUT_DIR/${edir}
  DATA_DIR=$OUTPUT_DIR/${edir}
  ANA_DATA_DIR=$ANALYSIS_DIR/${edir}

cd ${work_dir}
#################################################
# cat together the INPUT*-files
#################################################

cat > INPUT_ASS << end_input_ass

 &NUDGING
  lnudge  =.FALSE.,
  hnudgsta= 0.0,  hnudgend = 9.0,  tconbox = 180.0,
  lverif  =%VERIF%,
  ycdfdir = '${OBS_DIR}',
  llhn    =%LHN%, llhnverif=%LHN%, lhn_wweight=.true.,
  mveripr =3,
  rqrsgmax= 0.4,
  radar_in='${OBS_DIR}',
  hversta = 0.001, hverend = ${h_int},
  khumbal = 100,
  mruntyp = 1,
  ntpscor = 1,  ptpstop=400.0,  luvgcor=.TRUE.,
  ltipol  =.TRUE.,  tipolmx = 3.0,  wtukrsa = 3.0,  wtukrse = 1.0,
  ltipsu  =.TRUE.,  tipmxsu = 1.0,  wtuksua = 1.5,  wtuksue = 0.5,
                                    wtukara = 1.5,  wtukare = 0.5,
  msprpar = 1,  msprpsu = 0,
  gnudg   = 0.0006, 0.0012, 0.0006, 0.0006,
  gnudgsu = 0.0006, 0.0012, 0.0000, 0.0006,
  gnudgar = .0006, .0000, .0006, .0000,
  vcorls  = .333 , .333 , .04  , .04  ,  vcutof  = 0.75, 0.75, 1.0 , 1.0 ,
  vcorlsu = .013 , .013 , .002 ,.00001,  vcutosu = 0.75, 0.75, 4.0 ,0.001,
  vcsnisu = 2500., 2500., 9.   , 9.   ,
                                         rhvfac  = 1.0 , 0.0 , 0.83, 0.83,
  rhinfl  =    0.,   70.,    0.,    0.,  rhtfac  = 1.3 , 1.43, 1.3 , 1.3 ,
  rhiflsu =   70.,   70.,  100.,   70.,  rhtfsu  = 1.0 , 1.43, 1.0 , 1.0 ,
  fnondiv = 0.8  ,   cnondiv = 0.1    ,  cutofr  = 3.5 , 3.5 , 3.5 , 3.5 ,
  tnondiv = 1.1  ,                       cutofsu = 2.0 , 3.5 , 2.0 , 2.0 ,
  topobs  =  849., 1099.,  799.,  699.,
  botmod  = 1099., 1099., 1099.,  899.,
  lscadj  =.TRUE.,.TRUE.,.TRUE.,.FALSE.,
  dtqc    =  720.,                       qcvf    = 5.00, 1.00,10.00, 1.00,
  qcc     =  0.00,500.00,  0.00,  0.00,
  qccsu   =   12.,  500.,   12.,    .7,
  mqcorr92= 0,
  lsynop  =.true.,
  laircf  =.true.,
  ldribu  =.true.,
  ltemp   =.true.,
  lpilot  =.true.,
  lcd132  =.true., lcd133=.false., lcd136=.false., lcd146=.false.,
  maxmlo  = 1600,  maxsgo = 5000,  maxuso = 5000,  nolbc = 5,
  altopsu =  5000., 5000., 5000., 5000.,  thairh  = 0.,
  !maxmlo  = 3000,  maxsgo = 50000,  maxuso = 50000,  nolbc = 5,
  !doromx  = 100.0, 150.0, 150.0, 150.0, ! max. diff. of surface station from model orography (cf. altopsu)
  !altopsu = 5000., 5000., 5000., 5000., thairh  = 0.,
  exnlat  = 90.,  exslat =-90.,  exwlon = -180.,  exelon = 180.,
  lsurfa  =.false.,
  lt2m    =.false.,   ht2a = 0.,  ht2i = 1.,
  lrh2m   =.false.,  hh2a = 0.,  hh2i = 1.,
  lprecp  =.false., hprc = 0.,  raintp = 12.,
  lprodr =.true. ,  ldiasa =.true.,
  ionl    =167,   jonl =103,     ionl2 =167,    jonl2 =103,
  lff10m  =.false., hffa=0., hffi=1.,
  yfofdir='${ANA_DATA_DIR}',
 /
end_input_ass

cat > INPUT_DIA  << end_input_dia

 &DIACTL
   hincgp=0.25,
   lgplong=.true.,
   lgpshort=.false.,
   n0gp=0,
   n0meanval=0,
   nincmeanval=1,
   itype_diag_gusts=4,
   stationlist_tot= 0, 0, 53.633,  9.983, 'Hamburg Flughafen',
                    0, 0, 53.568,  9.974, 'Hamburg Geomatikum',
                    0, 0, 53.519,  10.103, 'Wettermast Hamburg',
 /
end_input_dia

cat > INPUT_EPS << end_input_eps
 &EPSCTL
  iepsmem=${I}, 
  iepstyp=2, 
  iepstot=%N_ENS%, 
  fac_plcov=1.00, 
  rmin_plcov=0.00, 
  rmax_plcov=1.00, fac_rootdp=1.000, 
  rmin_rootdp=0.000, 
  rmax_rootdp=2.000, 
  fac_lai=1.00,
  rmin_lai=0.00, 
  rmax_lai=8.00
 /
end_input_eps

cat > INPUT_DYN  << end_input_dyn  

 &DYNCTL
    l2tls=.TRUE.,
    lcond=.TRUE.,
    ldyn_bbc=.FALSE.,
    ldiabf_lh=.TRUE.,
    l_diff_Smag=.TRUE.,
    y_scalar_advect='BOTT2_STRANG', 
    lspubc=.TRUE.,
    itype_hdiff=2,
    hd_dhmax=250.,
    hd_corr_trcr_bd=0.0,
    hd_corr_t_bd=0.75,
    hd_corr_u_bd=0.75,
    hd_corr_p_bd=0.75,
    hd_corr_trcr_in=0.0,
    hd_corr_t_in=0.0,
    hd_corr_u_in=0.1,
    hd_corr_p_in=0.0,
    irunge_kutta=1,
    irk_order=3,
    iadv_order=5,
    itype_fast_waves=2,
    itype_bbc_w=114,
    nrdtau=5,
    xkd=0.1,
    rlwidth=10000.0,
    itype_outflow_qrsg=2,
 /
end_input_dyn

cat > INPUT_INI  << end_input_ini 

 &INICTL
    dtbak=25.0,
    dtfwd=25.0,
    ndfi=2,
    tspan=3600.000000,
    taus=3600.000000,
 /
end_input_ini

cat > INPUT_IO  << end_input_io

 &IOCTL
  lasync_io=.FALSE,
  ngribout=3,
  yform_read='apix',
  l_ke_in_gds=.FALSE.,
  yncglob_institution='Meteorologisches Insitut, Universität Hamburg',
  yncglob_title='First bacy run',
  yncglob_source='lmparbin_all',
  yncglob_contact='Tobias Sebastian Finn t.finn@meteowindow.com',
  yncglob_project_id='um0203',
  yncglob_references='Master thesis Tobias Finn'
  yncglob_experiment_id='%EXP_ID%',
  ncglob_realization=1,
 /
 &DATABASE
 /
 &GRIBIN
    lan_t_so0=.TRUE., lan_t_cl=.TRUE., lan_w_cl=.TRUE., lan_vio3=.TRUE.,
    lan_hmo3=.TRUE., lan_plcov=.TRUE., lan_lai=.TRUE., lan_rootdp=.TRUE.,
    lan_t_snow=.TRUE., lan_w_i=.TRUE., lan_w_snow=.TRUE., lan_rho_snow=.TRUE.,
    lan_w_so=.TRUE., lan_t_s=.FALSE.,
    hincbound=1.0,
    lchkini    = .TRUE.,  lchkbd    = .TRUE.,  lbdana=.FALSE.,
    lana_qi    = .TRUE.,  llb_qi    = .TRUE.,  lana_rho_snow=.FALSE., 
    lana_qr_qs = .TRUE.,  llb_qr_qs = .TRUE.,
    ydirbd='${BD_DIR}',
    ydirini='${INI_DIR}',
 /
 &GRIBOUT
    hcomb=0.0,${h_int},1.0,
    lanalysis=.FALSE.,
    lcheck=.TRUE.,
    lwrite_const=.TRUE.,
    l_fi_filter=.TRUE.,
    yform_write='api2',
    ydir='${DATA_DIR}',
    yvarml='U         ','V         ','W         ','T         ',
           'P         ','QV        ','QC        ','QI        ',
           'QR        ','QS        ','QG        ','Q_SEDIM   ',
           'CLC       ','TKE       ',
           'PS        ','T_SNOW    ','T_S       ','W_SNOW    ',
           'QV_S      ','W_I       ','RAIN_GSP  ','SNOW_GSP  ',
           'GRAU_GSP  ','PRR_GSP   ','PRS_GSP   ','PRG_GSP   ',
           'U_10M     ','V_10M     ','T_2M      ','TD_2M     ',
           'TMIN_2M   ','TMAX_2M   ','VMAX_10M  ','TCM       ',
           'TCH       ','CLCT      ','CLCH      ','CLCM      ',
           'CLCL      ','ALB_RAD   ','ASOB_S    ','ATHB_S    ',
           'ASOB_T    ','ATHB_T    ','APAB_S    ','TOT_PREC  ',
           'Z0        ','AUMFL_S   ','AVMFL_S   ','ASHFL_S   ',
           'ALHFL_S   ','HTOP_DC   ','RUNOFF_S  ','RUNOFF_G  ',
           'PMSL      ','T_G       ','HZEROCL   ','CLCT_MOD  ',
           'CLDEPTH   ','TDIV_HUM  ','TWATER    ','AEVAP_S   ',
           'TQI       ','TQC       ','TQV       ','TQR       ',
           'TQS       ','TQG       ','HBAS_SC   ','HTOP_SC   ',
           'DBZ_850   ','DBZ_CMAX  ','T_SO      ','W_SO      ',
           'FRESHSNW  ','RHO_SNOW  ','FOR_D     ','FOR_E     ',
           'H_SNOW    ','W_SO_ICE  ','RELHUM_2M ','ZHD       ',
           'ZTD       ','ZWD       ','CAPE_ML   ','CIN_ML    ',
           'CEILING   ','SDI_1     ','SDI_2     ','SNOWLMT   ',
           'ASWDIR_S  ','ASWDIFD_S ','ASWDIFU_S ',
    yvarpl='T         ','RELHUM    ','U         ','V         ',
           'FI        ','OMEGA     ',
    yvarzl='T         ','RELHUM    ','U         ','V         ',
           'P         ','W         ',
    yvarsl='SYNMSG',
    plev=200.0,  250.0,  300.0,  400.0,  500.0,  600.0,  700.0,  850.0,
         950.0,  975.0, 1000.0,
    zlev=500.0, 1000.0, 1500.0, 2000.0, 3000.0, 5000.0,
 /
 &GRIBOUT
    ncomb=0,${TIMESTEPS},300,
    lanalysis=.FALSE.,
    lcheck=.TRUE.,
    lwrite_const=.FALSE.,
    l_fi_filter=.TRUE.,
    yform_write='ncdf',
    ydir='${DATA_DIR}',
    ysuffix='_wm',
    ydomain='s',
    slon=0.25,
    slat=-0.45,
    elon=0.35,
    elat=-0.35,
    itype_vertint=1,
    yvarml='U         ','V         ','W         ','T         ',
           'P         ','QV        ','QC        ','QI        ',
           'QR        ','QS        ','QG        ','Q_SEDIM   ',
           'CLC       ','TKE       ',
           'PS        ','T_SNOW    ','T_S       ','W_SNOW    ',
           'QV_S      ','W_I       ','RAIN_GSP  ','SNOW_GSP  ',
           'GRAU_GSP  ','PRR_GSP   ','PRS_GSP   ','PRG_GSP   ',
           'U_10M     ','V_10M     ','T_2M      ','TD_2M     ',
           'TMIN_2M   ','TMAX_2M   ','VMAX_10M  ','TCM       ',
           'TCH       ','CLCT      ','CLCH      ','CLCM      ',
           'CLCL      ','ALB_RAD   ','ASOB_S    ','ATHB_S    ',
           'ASOB_T    ','ATHB_T    ','APAB_S    ','TOT_PREC  ',
           'Z0        ','AUMFL_S   ','AVMFL_S   ','ASHFL_S   ',
           'ALHFL_S   ','HTOP_DC   ','RUNOFF_S  ','RUNOFF_G  ',
           'PMSL      ','T_G       ','HZEROCL   ','CLCT_MOD  ',
           'CLDEPTH   ','TDIV_HUM  ','TWATER    ','AEVAP_S   ',
           'TQI       ','TQC       ','TQV       ','TQR       ',
           'TQS       ','TQG       ','HBAS_SC   ','HTOP_SC   ',
           'DBZ_850   ','DBZ_CMAX  ','T_SO      ','W_SO      ',
           'FRESHSNW  ','RHO_SNOW  ','FOR_D     ','FOR_E     ',
           'H_SNOW    ','W_SO_ICE  ','RELHUM_2M ','ZHD       ',
           'ZTD       ','ZWD       ','CAPE_ML   ','CIN_ML    ',
           'CEILING   ','SDI_1     ','SDI_2     ','SNOWLMT   ',
           'ASWDIR_S  ','ASWDIFD_S ','ASWDIFU_S ',
    yvarpl='',
    yvarzl='T         ','RELHUM    ','U         ','V         ',
           'P         ','W         ',
    yvarsl='',
    zlev=2.0, 10.0, 50.0, 110.0, 175.0, 250.0, 280.0,
 /
  &GRIBOUT
    hgrib=0.0,1.0,1.0,
    lanalysis=.false.,
    lcheck=.true.,
    lwrite_const=.false.,
    l_p_filter=.false.,
    l_fi_filter=.false.,
    luvmasspoint=.true.,
    nunit_of_time=13,
    yform_write='api2',
    ydir='${ANA_DATA_DIR}',
    yvarml='U         ','V         ','W         ','T         ',
           'P         ','QV        ','QC        ','QI        ',
           'QR        ','QS        ','QG        ','HHL       ',
           'RLAT      ','RLON      ','FIS       ',
           'PS        ','T_SNOW    ','T_S       ','W_SNOW    ',
           'QV_S      ','W_I       ','RAIN_GSP  ','SNOW_GSP  ',
           'GRAU_GSP  ','PRR_GSP   ','PRS_GSP   ','PRG_GSP   ',
           'U_10M     ','V_10M     ','T_2M      ','TD_2M     ',
           'TMIN_2M   ','TMAX_2M   ','VMAX_10M  ','TCM       ',
           'TCH       ','CLCT      ','CLCH      ','CLCM      ',
           'CLCL      ','ALB_RAD   ','ASOB_S    ','ATHB_S    ',
           'ASOB_T    ','ATHB_T    ','APAB_S    ','TOT_PREC  ',
           'Z0        ','AUMFL_S   ','AVMFL_S   ','ASHFL_S   ',
           'ALHFL_S   ','HTOP_DC   ','RUNOFF_S  ','RUNOFF_G  ',
           'PMSL      ','T_G       ','VIO3      ','HMO3      ',
           'LAI       ','HZEROCL   ','CLCT_MOD  ','CLDEPTH   ',
           'TDIV_HUM  ','TWATER    ','AEVAP_S   ','PLCOV     ',
           'ROOTDP    ','FR_LAND   ','SOILTYP   ','HSURF     ',
           'TQI       ','TQC       ','TQV       ','TQR       ',
           'TQS       ','TQG       ','HBAS_SC   ','HTOP_SC   ',
           'T_SO      ','W_SO      ','W_SO_ICE  ','FRESHSNW  ',
           'RHO_SNOW  ','H_SNOW    ','RELHUM_2M ','ZHD       ',
           'ZTD       ','ZWD       ','SNOWLMT   ','FOR_D     ',
           'FOR_E     ','H_ICE     ','T_ICE     ','DEPTH_LK  ',
           'FR_LAKE   ','ALB_DIF   ',
           'T_MNW_LK  ','T_WML_LK  ','T_BOT_LK  ','C_T_LK    ', 
           'H_ML_LK   ',
    yvarpl='',
    yvarzl='',
    yvarsl='',
 /
end_input_io

cat > INPUT_ORG  << end_input_org  

 &LMGRID
  startlat_tot=-0.96, startlon_tot=-0.743,
  pollat=36.063, pollon=-170.4150,
  dlat=0.00400, dlon=0.00400,
  ie_tot=500, je_tot=300, ke_tot=50,
  irefatm=1,
 /
 &RUNCTL
    dt=2.0,
    hstart=0.0,
    hstop=${h_int},
    idbg_level=2,
    ldatatypes=.true.,
    ldfi=.false.,
    ldiagnos=.FALSE.,
    ldump_ascii=.FALSE.,
    ldebug_io=.TRUE.,
    leps=$EPS
    lphys=.true.,
    lreproduce=.true.,
    luseobs=.true.,
    luse_rttov=.false.,
    nboundlines=3,
    ncomm_type=3,
    nprocx = $NPX,
    nprocy = $NPY,
    nprocio = $NPIO,
    ydate_ini='${ini_date}',
    ydate_bd='${bd_date}',
    !luse_radarfwo=.TRUE.,
 /
 &TUNING
    crsmin=150.,
    qc0=0.0002,
    qi0=0.0,
    gkwake=0.8,
    clc_diag  =   0.5,
    pat_len   = 500.0,
    tur_len   = 25.0,
    rlam_heat =   1.0,
    rlam_mom  =   0.0,
    rat_lam   =   1.0,
    rat_can   =   1.0,
    rat_sea   =  20.0,
    c_lnd     =   2.0,
    c_soil    =   1.0,
    c_sea     =   1.5,
    z0m_dia   =   0.2,
    crsmin    = 150.0,
    wichfakt  =   0.0,
    qc0       =   0.0002,
    q_crit    =   1.6,
    mu_rain   =   0.5,
    rain_n0_factor = 0.1,
    v0snow    =    20,
    tkhmin    =   0.4,
    tkmmin    =   0.4,
 /
end_input_org
 #&TUNING
    #c_soil=1.0,
    #clc_diag=0.50,
    #crsmin=150.,
    #mu_rain=0.5,
    #rain_n0_factor=0.1,
    #qc0=0.0002,
    #q_crit=1.60,
    #qi0=0.0,
    #rat_can=1.0,
    #rat_lam=1.0,
    #tur_len=150.0,
    #v0snow=20.0,
    #wichfakt=0.0,
    #gkwake=0.8,
 #/
#end_input_org


cat > INPUT_PHY  << end_input_phy

 &PHYCTL
    lgsp=.TRUE.,
      itype_gscp=4,
    lrad=.TRUE.,
      nradcoarse=1,
      lradf_avg=.FALSE.
      hincrad=0.1,
      lforest=.TRUE.,
      itype_albedo=1,
    ltur=.TRUE.,
      ninctura=1,
      lexpcor=.TRUE.,
      ltmpcor=.FALSE.,
      lprfcor=.FALSE.,
      lnonloc=.FALSE.,
      lcpfluc=.FALSE.,
      limpltkediff=.TRUE.,
      lprog_tke=.TRUE.,
      itype_turb=7,
      imode_turb=1,
      l3dturb=.TRUE.,
      l3dturb_metr=.TRUE.,
      itype_tran=2,
      imode_tran=1,
      itype_wcld=2,
      icldm_rad =4,
      icldm_turb=2,
      icldm_tran=0,
      itype_synd=2,
    lsoil=.TRUE.,
      itype_evsl=2,
      itype_trvg=2,
      lmulti_layer=.TRUE.,
      lmelt=.TRUE.,
      lmelt_var=.TRUE.,
      ke_soil = 7,
      czml_soil = 0.005, 0.02, 0.06, 0.18, 0.54, 1.62, 4.86, 14.58,
      lmulti_snow=.FALSE.,
      ke_snow=2,
    lconv=.TRUE.,
      lcape=.FALSE.,
      lconf_avg=.TRUE.,
      lconv_inst=.TRUE.,
      itype_conv=3,
      nincconv=10,
    llake=.FALSE.,
    lseaice=.FALSE.,
    lsso=.FALSE.,
      ltkesso=.FALSE.,
 /
end_input_phy

cat > INPUT_SAT  << end_input_sat

 &SATCTL
  num_sensors=1, itype_rttov=9,
  sat_input_01='MSG'     ,2,'SEVIRI',8, .true., .true., .true., .true.,
  nchan_input_01=1,2,3,4,5,6,7,8,
  lcon_clw=.true.,
 /
end_input_sat

#I=$(expr $I + 1)
((I=I+1))
done

cd ..

#################################################
# run the program
#################################################

#################################################

cat > %NAME%_$1_$2_job << ****
#! /bin/bash
#################################################
# load leveler commandos
#################################################
#SBATCH --job-name=%NAME%_%EXP_ID%
#SBATCH --partition=compute
#SBATCH --nodes=$NODES
#SBATCH --ntasks-per-node=$CPN
#SBATCH --time=08:00:00
#SBATCH --account=um0203
#SBATCH --output=$LOG_DIR/out_%j.out
#SBATCH --error=$LOG_DIR/err_%j.out

ulimit -s unlimited

# limit stacksize ... adjust to your programs need
source /sw/rhel6-x64/etc/profile.mistral
source /home/zmaw/u300636/cosmo_hh/code/load_modules_bullmx
#export GRIB_SAMPLES_PATH=${INT2LM_DIR}/1.13.1/samples/
export GRIB_DEFINITION_PATH=/home/zmaw/u300636/cosmo_hh/code/utilities/build/grib_api/share/grib_api/definitions
#export GRIB_DEFINITION_PATH=/home/zmaw/u300636/cosmo_hh/code/utilities/build/grib_api/definitions.edzw-1.18.0-3:${GRIB_DEFINITION_PATH}
#export GRIB_DEFINITION_PATH=${GRIB_DEFINITION_PATH}:/home/zmaw/u300636/cosmo_hh/code/utilities/build/grib_api/definitions.edzw-1.18.0-3
#export GRIB_DEFINITION_PATH=${GRIB_DEFINITION_PATH}:/home/zmaw/u300636/cosmo_hh/code/utilities/build/grib_api/definitions.edzw-1.18.0-3
export GRIB_SAMPLES_PATH=/home/zmaw/u300636/cosmo_hh/code/int2lm/1.13.1/samples/



I=$START_ENS
DET=$DET
until [[ \$I -gt $N_LOOP ]]; do
  if [ \$I -ge 10 ]; then
    Iens=0\${I}
  else
    Iens=00\${I}
  fi
  if [ \$DET = true -a \$I -eq $N_LOOP ]; then
    edir=det
  else
    edir=ens\${Iens}
  fi
  work_dir=$INPUT_DIR/\${edir}
  cd \${work_dir}
  rm -f YU* M_*
  srun --cpu_bind=cores -l --propagate=STACK \
	--distribution=block:cyclic $COSMO_DIR/lmparbin_all
  rc=\$?
  if [[ \$rc -ne 0 ]]; then
    exit \$rc
  fi

  #################################################
  # cleanup
  #################################################

  # rm -f INPUT_ORG INPUT_IO INPUT_DYN INPUT_DIA INPUT_PHY INPUT_INI
  # rm -f INPUT_ASS INPUT_SAT INPUT_EPS

  ((I=I+1))
done
## end of LOOP

****

chmod u+x %NAME%_$1_$2_job
sbatch %NAME%_$1_$2_job | grep -o '[0-9]*' >> pid_file
